### ISSUE TITLE
Connection to server lost, will attempt reconnection.

### ISSUE THREAD

**Issue by ForestQ** [TheNickOfTime/handbrake-web#142]
### Discussed in https://github.com/TheNickOfTime/handbrake-web/discussions/141

<div type='discussions-op-text'>

<sup>Originally posted by **ForestQ** August 16, 2024</sup>
Hi!
The worker on the same machine in the same Docker instance doesn't want to connect. I tried both 127.0.0.1 and the real IP. What should I do?

handbrake-web-worker  | [worker] The worker process has started.
handbrake-web-worker  | [worker] [server] Connection to server lost, will attempt reconnection...

```
  handbrake-server:
    image: ghcr.io/thenickoftime/handbrake-web-server:latest
    container_name: handbrake-web-server
    user: 0:0
    ports:
      - 9999:9999
    volumes:
      - /home/forestq/handbrake:/data
      - /mnt/storage2:/video #ensure this path is the same across all containers

  handbrake-worker:
    image: ghcr.io/thenickoftime/handbrake-web-worker:latest
    container_name: handbrake-web-worker
    user: 0:0
    environment:
      - WORKER_ID=server #give your worker a unique name
      - SERVER_URL=10.3.5.32 #set to the url or ip of your server
      - SERVER_PORT=9999 #if using a reverse proxy, this may be different than what is set above
    volumes:
      - /mnt/storage2:/video #ensure this path is the same across all containers
    depends_on:
      - handbrake-server
```</div>

**Comment by TheNickOfTime** [comment]
Hey, this was brought to my attention by another user in another issue - I believe the solution to this issue is to change:
```
- SERVER_URL=10.3.5.32 #set to the url or ip of your server
```
to:
```
- SERVER_URL=http://10.3.5.32 #set to the url or ip of your server
```

I will update the readme with this info when I get a chance. Also I think I'm going to make it so you can either include or omit `http://` in the next release for better flexibility.

**Comment by TheNickOfTime** [comment]
This issue will be addressed by #143 and #144 :)

**Comment by ForestQ** [comment]
ooops, SERVER_URL kind of implies it. )) thx

**Comment by TheNickOfTime** [comment]
No worries, thanks for bringing it to my attention, I can definitely account for this to work either way.
