### ISSUE TITLE
aarch64 Support

### ISSUE THREAD

**Issue by hagenman** [TheNickOfTime/handbrake-web#227]
### Is your feature request related to a problem that you are experiencing?
If yes, please provide a description of that problem.

### Describe your feature request
Describe how your idea works/functions, how it would present itself to a user, etc.
Would love to be able to deploy this docker image on aarch64.

### Provide additional context
If you have any additional information you would like to provide, or images you would like to attach, please put them here.

**Comment by TheNickOfTime** [comment]
Hey there, thank you for your feature request. I have worked exclusively with x86 hardware, so this simply hadn't occurred to me! I'll take a look into this as soon as I can - AFAIK it should be relatively simple to add builds for the different architectures. I'll link a PR here whenever development on this gets underway :)

**Comment by TheNickOfTime** [comment]
@hagenman the above PR should enable you to run the program on your ARM devices. I have no way of testing if this works, so it would be very helpful to me if you could pull the images from this PR and give it a try. To do this simply replace do the following in your docker compose file:

- Replace `ghcr.io/thenickoftime/handbrake-web-server:latest` with `ghcr.io/thenickoftime/handbrake-web-server:pr-230`
- Replace `ghcr.io/thenickoftime/handbrake-web-worker:latest` with `ghcr.io/thenickoftime/handbrake-web-worker:pr-230`

**Comment by hagenman** [comment]
I've tried to pull with both crictl pull and docker pull and get variants of 'manifest not found' and it looks like a Github action failed?  I'm trying to figure stuff out to make sure I didn't do anything wrong, hooray learning!

**Comment by TheNickOfTime** [comment]
Nah, this would be something on my end that isn't quite working right. I'll try a few more things and ping back here again.

**Comment by TheNickOfTime** [comment]
Hey there @hagenman, sorry for the delay but I've fixed the issue that was preventing you from pulling the image. Feel free to give it another go!

**Comment by hagenman** [comment]
Got it working!!!  Now have a 3-node cluster running in kubernetes!
![Screenshot_20240910_120905](https://github.com/user-attachments/assets/1cb322cd-95dd-4e36-8c9d-1ab36b4c7a39)

**Comment by TheNickOfTime** [comment]
Fantastic, I'll merge this and push a 0.7.1 release. Just remember to point your image tag back at latest or another version tag, since the pr image will be removed once it is closed.
